version: '2.0'

services:
  niu:
    build:
      context: ./
    depends_on:
      - ipfs
    ports:
      - "3000:3000"
    volumes:
      - './:/niu'
    working_dir: /niu
    command: [
      "npm", "start"
    ]

  niu-redis:
    image: redis:4.0.6
    ports:
      - "6379:6379"

  ipfs:
    image: ipfs/go-ipfs:latest
    volumes:
      - './data/ipfs:/data/ipfs'
    ports:
      - "4001:4001"
      - "8080:8080"
      - "8081:8081"
      - "5001:5001"
    command: [
      "--enable-pubsub-experiment"
    ]
